export enum AnalyticsEvent {
  MESSAGE_SENT = 'message_sent',

  PRODUCT_ACTIVE_MINUTE = 'product_active_minute',

  APP_LAUNCHED = 'cli.app_launched',
  FINGERPRINT_GENERATED = 'cli.fingerprint_generated',
  CHANGE_DIRECTORY = 'cli.change_directory',
  INVALID_COMMAND = 'cli.invalid_command',
  KNOWLEDGE_FILE_UPDATED = 'cli.knowledge_file_updated',
  LOGIN = 'cli.login',
  LOGIN_STARTED = 'cli.login_started',
  LOGIN_FAILED = 'cli.login_failed',
  LOGIN_TIMEOUT = 'cli.login_timeout',
  LOGIN_ABORTED = 'cli.login_aborted',
  SLASH_MENU_ACTIVATED = 'cli.slash_menu_activated',
  SLASH_COMMAND_USED = 'cli.slash_command_used',
  TERMINAL_BROKER_SPAWN_FAILED = 'cli.terminal_broker_spawn_failed',
  TERMINAL_WATCHDOG_FAILED = 'cli.terminal_watchdog_failed',
  TERMINAL_COMMAND_COMPLETED = 'cli.terminal_command_completed',
  UPDATE_CODEBUFF_FAILED = 'cli.update_codebuff_failed',
  FEEDBACK_BUTTON_HOVERED = 'cli.feedback_button_hovered',
  FOLLOWUP_CLICKED = 'cli.followup_clicked',
  SUGGESTED_PROMPT_SHOWN = 'cli.suggested_prompt_shown',
  SUGGESTED_PROMPT_CLICKED = 'cli.suggested_prompt_clicked',
  CLI_INLINE_AD_SLOT_ELIGIBLE = 'cli.inline_ad_slot_eligible',
  CREDIT_GRANT = 'backend.credit_grant',
  CREDIT_CONSUMED = 'backend.credit_consumed',
  MALFORMED_TOOL_CALL_JSON = 'backend.malformed_tool_call_json',
  UNKNOWN_TOOL_CALL = 'backend.unknown_tool_call',

  ADVISORY_LOCK_CONTENTION = 'backend.advisory_lock_contention',
  TRANSACTION_RETRY_THRESHOLD_EXCEEDED = 'backend.transaction_retry_threshold_exceeded',

  SUBSCRIPTION_CREATED = 'backend.subscription_created',
  SUBSCRIPTION_CANCELED = 'backend.subscription_canceled',
  SUBSCRIPTION_PAYMENT_FAILED = 'backend.subscription_payment_failed',
  SUBSCRIPTION_BLOCK_CREATED = 'backend.subscription_block_created',
  SUBSCRIPTION_BLOCK_LIMIT_HIT = 'backend.subscription_block_limit_hit',
  SUBSCRIPTION_WEEKLY_LIMIT_HIT = 'backend.subscription_weekly_limit_hit',
  SUBSCRIPTION_CREDITS_MIGRATED = 'backend.subscription_credits_migrated',
  SUBSCRIPTION_TIER_CHANGED = 'backend.subscription_tier_changed',

  SIGNUP = 'web.signup',

  AUTH_LOGIN_STARTED = 'auth.login_started',
  AUTH_LOGOUT_COMPLETED = 'auth.logout_completed',

  COOKIE_CONSENT_ACCEPTED = 'cookie_consent.accepted',
  COOKIE_CONSENT_DECLINED = 'cookie_consent.declined',

  ONBOARDING_STEP_COMPLETED = 'onboarding_step_completed',
  ONBOARDING_STEP_VIEWED = 'onboarding_step_viewed',
  ONBOARDING_PM_SELECTED = 'onboarding_pm_selected',
  ONBOARDING_EDITOR_OPENED = 'onboarding_editor_opened',

  ONBOARD_PAGE_CD_COMMAND_COPIED = 'onboard_page.cd_command_copied',
  ONBOARD_PAGE_RUN_COMMAND_COPIED = 'onboard_page.run_command_copied',
  ONBOARD_PAGE_INSTALL_COMMAND_COPIED = 'onboard_page.install_command_copied',

  CODEBUFF_REFERRER_ATTRIBUTED = 'codebuff.referrer_attributed',

  INSTALL_DIALOG_CD_COMMAND_COPIED = 'install_dialog.cd_command_copied',
  INSTALL_DIALOG_RUN_COMMAND_COPIED = 'install_dialog.run_command_copied',
  INSTALL_DIALOG_INSTALL_COMMAND_COPIED = 'install_dialog.install_command_copied',

  HOME_FEATURE_LEARN_MORE_CLICKED = 'home.feature_learn_more_clicked',
  HOME_INSTALL_COMMAND_COPIED = 'home.install_command_copied',
  HOME_TRY_FREE_CLICKED = 'home.try_free_clicked',
  HOME_TESTIMONIAL_CLICKED = 'home.testimonial_clicked',
  HOME_CTA_INSTALL_GUIDE_CLICKED = 'home.cta_install_guide_clicked',
  HOME_COMPETITION_TAB_CHANGED = 'home.competition_tab_changed',

  DEMO_TERMINAL_COMMAND_EXECUTED = 'demo_terminal.command_executed',
  DEMO_TERMINAL_HELP_VIEWED = 'demo_terminal.help_viewed',
  DEMO_TERMINAL_OPTIMIZE_REQUESTED = 'demo_terminal.optimize_requested',
  DEMO_TERMINAL_FIX_MEMORY_LEAK = 'demo_terminal.fix_memory_leak',
  DEMO_TERMINAL_REFACTOR_REQUESTED = 'demo_terminal.refactor_requested',
  DEMO_TERMINAL_FEATURE_REQUESTED = 'demo_terminal.feature_requested',
  DEMO_TERMINAL_THEME_CHANGED = 'demo_terminal.theme_changed',

  TOAST_SHOWN = 'toast.shown',

  AGENT_RUN_VALIDATION_ERROR = 'api.agent_run_validation_error',
  AGENT_RUN_CREATION_ERROR = 'api.agent_run_creation_error',
  AGENT_RUN_COMPLETION_ERROR = 'api.agent_run_completion_error',
  ME_VALIDATION_ERROR = 'api.me_validation_error',
  CHAT_COMPLETIONS_AUTH_ERROR = 'api.chat_completions_auth_error',
  CHAT_COMPLETIONS_VALIDATION_ERROR = 'api.chat_completions_validation_error',
  CHAT_COMPLETIONS_INSUFFICIENT_CREDITS = 'api.chat_completions_insufficient_credits',
  CHAT_COMPLETIONS_GENERATION_STARTED = 'api.chat_completions_generation_started',
  CHAT_COMPLETIONS_ERROR = 'api.chat_completions_error',

  USAGE_API_AUTH_ERROR = 'api.usage_auth_error',

  WEB_SEARCH_AUTH_ERROR = 'api.web_search_auth_error',
  WEB_SEARCH_VALIDATION_ERROR = 'api.web_search_validation_error',
  WEB_SEARCH_INSUFFICIENT_CREDITS = 'api.web_search_insufficient_credits',
  WEB_SEARCH_ERROR = 'api.web_search_error',

  DOCS_SEARCH_REQUEST = 'api.docs_search_request',
  DOCS_SEARCH_AUTH_ERROR = 'api.docs_search_auth_error',
  DOCS_SEARCH_VALIDATION_ERROR = 'api.docs_search_validation_error',
  DOCS_SEARCH_INSUFFICIENT_CREDITS = 'api.docs_search_insufficient_credits',
  DOCS_SEARCH_ERROR = 'api.docs_search_error',

  GRAVITY_INDEX_REQUEST = 'api.gravity_index_request',
  GRAVITY_INDEX_AUTH_ERROR = 'api.gravity_index_auth_error',
  GRAVITY_INDEX_VALIDATION_ERROR = 'api.gravity_index_validation_error',
  GRAVITY_INDEX_ERROR = 'api.gravity_index_error',

  FEEDBACK_SUBMITTED = 'api.feedback_submitted',
  FEEDBACK_AUTH_ERROR = 'api.feedback_auth_error',
  FEEDBACK_VALIDATION_ERROR = 'api.feedback_validation_error',

  LOGS_INGEST_AUTH_ERROR = 'api.logs_ingest_auth_error',
  LOGS_INGEST_VALIDATION_ERROR = 'api.logs_ingest_validation_error',

  ADS_API_AUTH_ERROR = 'api.ads_auth_error',
  ADS_FETCH_COMPLETED = 'ads.fetch_completed',
  ADS_IMPRESSION_RECORDED = 'ads.impression_recorded',
  ADS_CLICKED = 'ads.clicked',
  ADS_FIRST_PARTY_DECISION = 'ads.first_party_decision',
  ADS_FIRST_PARTY_SETTLEMENT = 'ads.first_party_settlement',
  ADS_FIRST_PARTY_VIEW_ACK = 'ads.first_party_view_ack',

  TOKEN_COUNT_REQUEST = 'api.token_count_request',
  TOKEN_COUNT_AUTH_ERROR = 'api.token_count_auth_error',
  TOKEN_COUNT_VALIDATION_ERROR = 'api.token_count_validation_error',
  TOKEN_COUNT_ERROR = 'api.token_count_error',

  FREEBUFF_REFERRER_ATTRIBUTED = 'freebuff.referrer_attributed',

  FREEBUFF_REFERRAL_REDEEMED = 'freebuff.referral.redeemed',
  FREEBUFF_REFERRAL_REDEEM_FAILED = 'freebuff.referral.redeem_failed',
  FREEBUFF_REFERRAL_SOCK_SIGNAL = 'freebuff.referral.sock_signal',
  FREEBUFF_GET_STARTED_VIEWED = 'freebuff.get_started_viewed',
  FREEBUFF_GET_STARTED_SIGN_IN_CLICKED = 'freebuff.get_started_sign_in_clicked',
  FREEBUFF_GET_STARTED_SIGNED_IN = 'freebuff.get_started_signed_in',
  FREEBUFF_GET_STARTED_ELIGIBILITY_RESOLVED = 'freebuff.get_started_eligibility_resolved',
  FREEBUFF_GET_STARTED_CONNECT_GITHUB_CLICKED = 'freebuff.get_started_connect_github_clicked',
  FREEBUFF_GET_STARTED_INSTALL_COMMAND_COPIED = 'freebuff.get_started_install_command_copied',
  FREEBUFF_GET_STARTED_WEB_CLICKED = 'freebuff.get_started_web_clicked',
  FREEBUFF_GET_STARTED_HELP_EXPANDED = 'freebuff.get_started_help_expanded',
  FREEBUFF_GET_STARTED_EDITOR_CLICKED = 'freebuff.get_started_editor_clicked',

  FREEBUFF_CHAT_TITLE_GENERATED = 'freebuff.chat_title_generated',

  FREEBUFF_CLI_INSTALL_COMMAND_COPIED = 'freebuff.cli_install_command_copied',

  FREEBUFF_ENTERPRISE_CONTACT_SUBMITTED = 'freebuff.enterprise_contact_submitted',

  FREEBUFF_DESKTOP_DOWNLOAD_CLICKED = 'freebuff.desktop_download_clicked',

  FREEBUFF_WEB_GATE_REDIRECT_CLICKED = 'freebuff.web_gate_redirect_clicked',

  FREEBUFF_WEB_ONBOARDING_STEP = 'freebuff.web_onboarding_step',
  FREEBUFF_WEB_ONBOARDING_FINISHED = 'freebuff.web_onboarding_finished',

  FREEBUFF_WEB_TOUR_STEP = 'freebuff.web_tour_step',
  FREEBUFF_WEB_TOUR_FINISHED = 'freebuff.web_tour_finished',

  FREEBUFF_BOOKMARK_GATE_SHOWN = 'freebuff.bookmark_gate_shown',
  FREEBUFF_BOOKMARK_GATE_CONFIRMED = 'freebuff.bookmark_gate_confirmed',

  FREEBUFF_CLOUD_CONNECT_REPO_CLICKED = 'freebuff.cloud_connect_repo_clicked',
  FREEBUFF_CLOUD_BLANK_PROJECT_CLICKED = 'freebuff.cloud_blank_project_clicked',

  FREEBUFF_HOME_INSTALL_COMMAND_COPIED = 'freebuff.home_install_command_copied',
  FREEBUFF_HOME_GITHUB_CLICKED = 'freebuff.home_github_clicked',
  FREEBUFF_HOME_INSTALL_GUIDE_EXPANDED = 'freebuff.home_install_guide_expanded',
  FREEBUFF_HOME_FAQ_OPENED = 'freebuff.home_faq_opened',

  FREEBUFF_HOME_SAVINGS_CTA_CLICKED = 'freebuff.home_savings_cta_clicked',

  FREEBUFF_ATTRIBUTED = 'freebuff.attributed',
  FREEBUFF_AFFILIATE_SIGNUP = 'freebuff.affiliate.signup',
  FREEBUFF_AFFILIATE_ACTIVATION = 'freebuff.affiliate.activation',
  FREEBUFF_REDDIT_FUNNEL_CLI_INSTALLED = 'freebuff.reddit_funnel.cli_installed',
  FREEBUFF_REDDIT_FUNNEL_LOGIN = 'freebuff.reddit_funnel.login',
  FREEBUFF_REDDIT_FUNNEL_SIGN_UP = 'freebuff.reddit_funnel.sign_up',
  FREEBUFF_REDDIT_FUNNEL_FIRST_PROMPT = 'freebuff.reddit_funnel.first_prompt',
  FREEBUFF_REDDIT_FUNNEL_RETENTION_1D = 'freebuff.reddit_funnel.retention_1d',
  FREEBUFF_REDDIT_FUNNEL_RETENTION_7D = 'freebuff.reddit_funnel.retention_7d',
  FREEBUFF_REDDIT_FUNNEL_RETENTION_24D = 'freebuff.reddit_funnel.retention_24d',
  FREEBUFF_REDDIT_FUNNEL_FIRST_PROMPT_CLI = 'freebuff.reddit_funnel.first_prompt_cli',
  FREEBUFF_REDDIT_FUNNEL_FIRST_PROMPT_WEB = 'freebuff.reddit_funnel.first_prompt_web',
  FREEBUFF_REDDIT_FUNNEL_FIRST_PROMPT_CHAT = 'freebuff.reddit_funnel.first_prompt_chat',
  FREEBUFF_REDDIT_FUNNEL_RETENTION_1D_CLI = 'freebuff.reddit_funnel.retention_1d_cli',
  FREEBUFF_REDDIT_FUNNEL_RETENTION_7D_CLI = 'freebuff.reddit_funnel.retention_7d_cli',
  FREEBUFF_REDDIT_FUNNEL_RETENTION_24D_CLI = 'freebuff.reddit_funnel.retention_24d_cli',
  FREEBUFF_REDDIT_FUNNEL_GRAVITY_AD_CLICK = 'freebuff.reddit_funnel.gravity_ad_click',

  FREEBUFF_CHAT_ADS_EXPERIMENT_EXPOSED = 'freebuff.chat_ads.experiment_exposed',
  FREEBUFF_CHAT_ADS_AD_SHOWN = 'freebuff.chat_ads.ad_shown',

  DESKTOP_APP_LAUNCHED = 'desktop.app_launched',
  DESKTOP_LOGIN_STARTED = 'desktop.login_started',
  DESKTOP_LOGIN = 'desktop.login',
  DESKTOP_LOGIN_FAILED = 'desktop.login_failed',
  DESKTOP_LOGOUT = 'desktop.logout',
  DESKTOP_THREAD_CREATED = 'desktop.thread_created',
  DESKTOP_THREAD_TITLED = 'desktop.thread_titled',
  DESKTOP_PROJECT_OPENED = 'desktop.project_opened',
  DESKTOP_PROJECT_REMOVED = 'desktop.project_removed',
  DESKTOP_TURN_COMPLETED = 'desktop.turn_completed',
  DESKTOP_FAILED_TURN_RECOVERY = 'desktop.failed_turn_recovery',
  DESKTOP_HARNESS_CHANGED = 'desktop.harness_changed',
  DESKTOP_MODEL_CHANGED = 'desktop.model_changed',
  DESKTOP_SKILL_RUN = 'desktop.skill_run',
  DESKTOP_QUEUE_SEND_NOW = 'desktop.queue_send_now',
  DESKTOP_FEATURE_USED = 'desktop.feature_used',
  DESKTOP_AUTORUN_TOGGLED = 'desktop.autorun_toggled',
  DESKTOP_AUTORUN_SCOPE_SET = 'desktop.autorun_scope_set',
  DESKTOP_CODEX_RESOLUTION = 'desktop.codex_resolution',
  DESKTOP_AD_SHOWN = 'desktop.ad_shown',
  DESKTOP_AD_CLICKED = 'desktop.ad_clicked',
  DESKTOP_INLINE_AD_SLOT_ELIGIBLE = 'desktop.inline_ad_slot_eligible',
  DESKTOP_SHUTDOWN_TURNS_ABORTED = 'desktop.shutdown_turns_aborted',
  DESKTOP_ORPHANS_REAPED = 'desktop.orphans_reaped',
  DESKTOP_WORKTREES_RECLAIMED = 'desktop.worktrees_reclaimed',
  DESKTOP_TURNS_RESURRECTED = 'desktop.turns_resurrected',
  DESKTOP_TURN_STALLED = 'desktop.turn_stalled',
  DESKTOP_TURN_BACKGROUND_WAIT = 'desktop.turn_background_wait',
  DESKTOP_EVENT_LOOP_HEALTH = 'desktop.event_loop_health',
  DESKTOP_THREADS_AUTO_ARCHIVED = 'desktop.threads_auto_archived',
  DESKTOP_DELIVERY_CONFLICT_CHANGED = 'desktop.delivery_conflict_changed',

  FLUSH_FAILED = 'common.flush_failed',
}
