export const PROFIT_MARGIN = 0.055

export const REQUEST_CREDIT_SHOW_THRESHOLD = 1
export const MAX_DATE = new Date(86399999999999)
export const BILLING_PERIOD_DAYS = 30
export const SESSION_MAX_AGE_SECONDS = 30 * 24 * 60 * 60
export const SESSION_TIME_WINDOW_MS = 30 * 60 * 1000
export const SIGNUP_FREE_CREDITS_GRANT = 0
export const SIGNUP_CREDIT_MIN_GITHUB_ACCOUNT_AGE_MONTHS = 4

export const DEFAULT_FREE_CREDITS_GRANT = 0

export const CREDIT_PRICING = {
  CENTS_PER_CREDIT: 1,
  MIN_PURCHASE_CREDITS: 100,
  DISPLAY_RATE: '$0.01 per credit',
} as const
