
export const MAX_RETRIES_PER_MESSAGE = 3

export const RETRY_BACKOFF_BASE_DELAY_MS = 1000

export const RETRY_BACKOFF_MAX_DELAY_MS = 8000

export const RECONNECTION_MESSAGE_DURATION_MS = 2000

export const RECONNECTION_RETRY_DELAY_MS = 500
